version: '3.8'
services:
  prism:
    image: stoplight/prism:5
    command: mock -h 0.0.0.0 /data/openapi.yaml
    ports:
      - "4010:4010"
    volumes:
      - ../openapi.yaml:/data/openapi.yaml:ro

